name: simple logger action

on: 
  pull_request:
    paths:
      - .github/workflows/python/simple-logger-action.yaml
      - python/**
  push:
    paths:
      - .github/workflows/python/simple-logger-action.yaml
      - python/**

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      
      - name: Show When This Ran
        run: date
      
      - name: Multiple Commands
        run: |
          echo "This is my first GitHub Action!"
          echo "Current directory: $PWD"
          echo "Let's list some files:"
          ls -la