name: simple logger action

permissions:
  contents: write

on: 
  pull_request:
    paths:
      - .github/workflows/python-simple-logger-action.yaml
      - python/simpler-logger/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/python-simple-logger-action.yaml
      - python/simpler-logger/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.4
        with:
          prefix: python-simpler-logger-
          log-path: python/simpler-logger
          release-branch: main
          dev-branch: main

      - name: Get Version2
        id: version2
        shell: bash
        run: |
          VERSION=$(docker run -v $(pwd):/repo codacy/git-version /bin/git-version \
            --folder /repo \
            --prefix python-simpler-logger- \
            --release-branch main)
          
          # Extract version number and combine with prefix
          CLEAN_VERSION="python-simpler-logger-$(echo $VERSION | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
          
          echo "new-version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
          echo "New Version: $CLEAN_VERSION"
          echo "Raw Version: $VERSION"

      - name: Display Version
        run: |
          echo "Current version: ${{ steps.version.outputs.version }}"
          echo "Clean version: ${{ steps.version2.outputs.new-version }}"

      - name: Create and Push Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{ steps.version2.outputs.new-version }} -m "Release ${{ steps.version2.outputs.new-version }}"
          git push origin ${{ steps.version2.outputs.new-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}