name: simple logger action

# Add permissions block at the top level
permissions:
  contents: write    # This gives permission to push tags

on: 
  pull_request:
    paths:
      - .github/workflows/python-simple-logger-action.yaml
      - python/simpler-logger/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/python-simple-logger-action.yaml
      - python/simpler-logger/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.4
        with:
          prefix: python-simpler-logger
          log-path: python/simpler-logger

      - name: Get Version2
        id: version
        shell: bash
        run: |
          export VERSION=$(docker run -v $(pwd):/repo codacy/git-version /bin/git-version \
            --folder /repo \
            --release-branch main)

          echo "::set-output name=new-version::$VERSION"
          echo "New Version: $VERSION"

      - name: Display Version
        run: |
          echo "Current version: ${{ steps.version.outputs.version }}"

      - name: Create Tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}